-- SELECT를 통한 테이블 데이터 복사
-- CREATE TABLE ... AS SELECT
-- CREATE TABLE 새 테이블명 AS SELECT 복사할 열 FROM 원본 테이블명 WEHRE 조건

-- 테이블 복사 : 기본키는 복사 안됨(제약 조건 따로 추가)
CREATE TABLE NEWBOOK AS
SELECT * FROM BOOK2 WHERE bookDate >= '2019-01-01';

SELECT * FROM NEWBOOK;

-- 제약조건은 복사되지 않으므로 수정 작업
ALTER TABLE NEWBOOK
ADD CONSTRAINT PK_NEWBOOK_BOOKNO PRIMARY KEY(BOOKNO);

-- NEWBOOK 데이터 삭제 - 모든 데이터 삭제
DELETE FROM NEWBOOK;

SELECT * FROM NEWBOOK;

-- 빈테이블에 데이터 저장 - 다른 테이블의 SELECT를 통해서 저장
-- 데이터를 저장할 테이블과 SELECT되는 테이블의 구조가 같을 경우
-- BOOK2 테이블과 NEWBOOK 테이블이 동일한 구조
INSERT INTO NEWBOOK SELECT * FROM BOOK2;

-- 테이블 생성
-- BOOK2 테이블의 BOOKNO, BOOKNAME 두 속성을 새로 구성하는 테이블의 구조와 데이터로 사용

CREATE TABLE NEWBOOK2
AS SELECT BOOKNO, BOOKNAME FROM BOOK2;

SELECT * FROM NEWBOOK2;

DELETE FROM NEWBOOK2;

-- NEWBOOK2 테이블에 BOOK2테이블의 BOOKNO, BOOKNAME을 복사해서 저장하시오
INSERT INTO NEWBOOK2(BOOKNO, BOOKNAME)
SELECT BOOKNO, BOOKNAME FROM BOOK2

SELECT BOOKNO, BOOKNAME, PUBNO
FROM BOOK2

